---
# Uninstall FFmpeg and clean up

- name: Remove FFmpeg binaries and symlinks
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ffmpeg_bin_dir }}/ffmpeg"
    - "{{ ffmpeg_bin_dir }}/ffprobe"
    - "{{ ffmpeg_bin_dir }}/x264"
    - "{{ ffmpeg_bin_dir }}/x265"
  tags:
    - remove_binaries

- name: Remove FFmpeg directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ffmpeg_build_dir }}"
    - "{{ ffmpeg_source_dir }}"
  tags:
    - remove_dirs

- name: Remove system FFmpeg package
  ansible.builtin.apt:
    name: ffmpeg
    state: absent
  become: true
  when: not ffmpeg_compile_codecs

- name: Remove apt dependencies
  ansible.builtin.apt:
    name: "{{ ffmpeg_deps }}"
    state: absent
    autoremove: true
  become: true
  when: ffmpeg_remove_deps
  tags:
    - remove_deps
