---
# Update FFmpeg by reinstalling

- name: Remove existing installation
  ansible.builtin.include_tasks: uninstall.yml
  args:
    apply:
      tags:
        - remove_dirs
        - remove_binaries

- name: Install fresh FFmpeg
  ansible.builtin.include_tasks: install.yml
